### PR TITLE
Brandon Sample Apps 25Mar2016

### PR DESCRIPTION
**Pull request by brminnick**
Added Beacon Funding Sample App
Added Smarter Security Sample App
Updated SimpleUITestApp

### CODE REVIEW

**Comment by brminnick** [comment]
@glennwester Can you review this pull request?

**Comment by IanLeatherbury** [comment]
@brminnick can you change the titles of these applications to describe what functions they show off?

**Comment by IanLeatherbury** [comment]
Also, slacked it to you, but please add a .gitignore to the packages folder.

**Comment by glennwester** [comment]
* readme.md file **check**
* metadata.xml file **check**
* Screenshots folder **check**
* gitignore needed on packages as Ian mentioned. The check in is enormous due to the package .dlls

**Comment by brminnick** [comment]
@glennwester Should be good to go! I refactored the app names and removed the packages folder.

**Comment by glennwester** [comment]
Thanks @brminnick merging!

**Pull request merged**
